// English translations for the tracked Arabic ranking keywords.
// Keyed on the exact `keywords.text` strings stored in the DB so lookups match 1:1.
// Unknown keywords fall back to "" (the English cell renders empty) — safe by design.
const KEYWORD_EN: Record<string, string> = {
  "إغلاق صفقات التداول": "Closing trading positions",
  "احتيال منصات التداول": "Trading platform fraud",
  "استرجاع أموال التداول": "Recovering trading funds",
  "استرجاع أموال الفوركس": "Recovering forex funds",
  "استرداد خسائر التداول": "Recovering trading losses",
  "استشارة لاسترداد الأموال": "Fund recovery consultation",
  "التلاعب بصفقات التداول": "Manipulating trading positions",
  "تجميد حساب التداول": "Freezing a trading account",
  "تصفية حساب التداول": "Liquidating a trading account",
  "شكوى ضد شركة تداول": "Complaint against a trading company",
  "شركة تداول مرخصة": "Licensed trading company",
  "منصة تداول مرخصة": "Licensed trading platform",
  "علامات نصب التداول": "Signs of a trading scam",
  "عمولة سحب التداول": "Trading withdrawal commission",
  "محامي شركات التداول": "Lawyer for trading companies",
  "مشاكل سحب التداول": "Trading withdrawal problems",
  "وسيط تداول لا يرد": "Unresponsive trading broker",

  // --- Country-specific keywords (added 2026-07-14). Keyed on exact Ahrefs text (typos incl.). ---
  // Saudi Arabia (SA)
  "استرجاع اموال التداول في السعودية": "Recover trading funds in Saudi Arabia",
  "استعادة الأموال بعد الاحتيال بنك الأهلي في السعودية": "Recover funds after fraud – Al Ahli Bank, Saudi Arabia",
  "استعادة الأموال بعد الاحتيال بنك الراجحي في السعودية": "Recover funds after fraud – Al Rajhi Bank, Saudi Arabia",
  "التداول حقيقي ام كذب في السعودية": "Is trading real or fake in Saudi Arabia",
  "تعرضت للنصب مع موقع تداول في السعودية ماذا افعل": "Scammed by a trading site in Saudi Arabia, what do I do",
  "تعرضت للنصب والاحتيال مع شركة تداول في السعودية": "Scammed and defrauded by a trading company in Saudi Arabia",
  "خسرت كل فلوسي في التداول في السعودية": "I lost all my money trading in Saudi Arabia",
  "شركة تداول نصب في السعودية": "Trading company scam in Saudi Arabia",
  "محامي لاسترجاع الأموال من التداول في السعودية": "Lawyer to recover trading funds in Saudi Arabia",
  "نصب تداول العملات في السعودية": "Currency trading scam in Saudi Arabia",
  "هل ممكن استرجع اموال بعد الخسارة مع شركة تداول في السعودية ؟": "Can I recover money after losses with a trading company in Saudi Arabia?",
  "يطلبون ايداع لحتى اقدر اسحب من شركة تداول في السعودية": "They demand a deposit before I can withdraw from a trading company in Saudi Arabia",
  // Qatar (QA)
  "استرجاع اموال التداول في قطر": "Recover trading funds in Qatar",
  "استرجاع اموال الفوركس في قطر": "Recover forex funds in Qatar",
  "استرداد اموال التداول في قطر": "Recover trading funds in Qatar",
  "أسماء شركات التداول النصابة في قطر": "Names of scam trading companies in Qatar",
  "خسرت اموالي في البورصة في قطر": "I lost my money in the stock market in Qatar",
  "شركات تداول مرخصة في قطر": "Licensed trading companies in Qatar",
  "شركة تداول نصب فس قطر": "Trading company scam in Qatar",
  "طريقة استرجاع الفلوس من شركات التداول في قطر": "How to recover money from trading companies in Qatar",
  "محامي استرجاع أموال في قطر": "Fund recovery lawyer in Qatar",
  "هل ممكن استرجع اموال بعد الخسارة مع شركة تداول في قطر ؟": "Can I recover money after losses with a trading company in Qatar?",
  "وكالة استرداد أموال من شركات الفوركس النصابة في قطر": "Agency to recover funds from scam forex companies in Qatar",
  "يطلبون ايداع لحتى اقدر اسحب من شركة تداول في قطر": "They demand a deposit before I can withdraw from a trading company in Qatar",
  // Oman (OM)
  "اريد استرجاع اموالي بعد الاحتيال في سلطنة عمان": "I want to recover my money after fraud in Oman",
  "استرداد الأموال من شركات التداول سلطنة عمان": "Recover funds from trading companies in Oman",
  "شركة تداول في سلطنة عمان نصب": "Trading company scam in Oman",
  "طريقة استرجاع الفلوس من شركات التداول في سلطنة عمان": "How to recover money from trading companies in Oman",
  "طريقه ارجاع حساب في التداول في سلطنة عمان": "How to restore a trading account in Oman",
  "كيف اسحب الفلوس من منصة التداول في سلطنة عمان": "How to withdraw money from a trading platform in Oman",
  "كيفية استرجاع أموالك من شركات التداول النصابة في سلطنة عمان": "How to recover your money from scam trading companies in Oman",
  "محامي تداول في سلطنة عمان": "Trading lawyer in Oman",
  "ممكن استرجع اموال بعد الخسارة مع شركة تداول في سلطنة عمان ؟": "Can I recover money after losses with a trading company in Oman?",
  "نصب شركة تداول في سلطنة عمان": "Trading company scam in Oman",
  "هل التداول ممنوع في سلطنة عمان": "Is trading banned in Oman",
  "يطلبون ايداع لحتى اقدر اسحب من شركة تداول في سلطنة عمان": "They demand a deposit before I can withdraw from a trading company in Oman",
  // Kuwait (KW)
  "استرجاع الاموال من شركات التداول في الكويت": "Recover funds from trading companies in Kuwait",
  "استرجاع اموال التداول في الكويت": "Recover trading funds in Kuwait",
  "استرداد الأموال من منصات التداول في الكويت": "Recover funds from trading platforms in Kuwait",
  "ردو فلوسي بعد النصب في الكويت": "Get my money back after a scam in Kuwait",
  "ردولي فلوسي بعد الاحتيال في الكويت": "Get my money back after fraud in Kuwait",
  "سحب اموال التداول في الكويت": "Withdraw trading funds in Kuwait",
  "شلون ارجع فلوسي بعد الاحتيال في الكويت": "How do I get my money back after fraud in Kuwait",
  "كيف اسحب فلوسي من الفوركس في الكويت": "How to withdraw my money from forex in Kuwait",
  "محامي استرجاع اموال التداول في الكويت": "Lawyer to recover trading funds in Kuwait",
  "محامي فوركس تداول في الكويت": "Forex trading lawyer in Kuwait",
  "هل ممكن استرجع اموال بعد الخسارة مع شركة تداول في الكويت ؟": "Can I recover money after losses with a trading company in Kuwait?",
  "يطلبون ايداع لحتى اقدر اسحب من شركة تداول في الكويت": "They demand a deposit before I can withdraw from a trading company in Kuwait",
  // Bahrain (BH)
  "استرجاع الاموال من شركات التداول في البحرين": "Recover funds from trading companies in Bahrain",
  "استرجاع اموال الفوركس والتداول في البحرين": "Recover forex and trading funds in Bahrain",
  "استرجاع اموال النصب والاحتيال في البحرين": "Recover money from scams and fraud in Bahrain",
  "استرداد الاموال من شركات التداول في البحرين": "Recover funds from trading companies in Bahrain",
  "النصب والاحتيال في التداول في البحرين": "Scams and fraud in trading in Bahrain",
  "تقديم شكوى ضد شركات التداول في البحرين": "Filing a complaint against trading companies in Bahrain",
  "شركات تداول في البحرين": "Trading companies in Bahrain",
  "شركة تداول نصب في البحرين": "Trading company scam in Bahrain",
  "محامي استرجاع اموال التداول في البحرين": "Lawyer to recover trading funds in Bahrain",
  "محامي استرداد اموال التداول في البحرين": "Lawyer to recover trading funds in Bahrain",
  "هل ممكن استرجع اموال بعد الخسارة مع شركة تداول في البحرين ؟": "Can I recover money after losses with a trading company in Bahrain?",
  "يطلبون ايداع لحتى اقدر اسحب من شركة تداول في البحرين": "They demand a deposit before I can withdraw from a trading company in Bahrain",
  // United Arab Emirates (AE)
  "استرجاع الأموال من شركات التداول في الامارات": "Recover funds from trading companies in the UAE",
  "استرداد اموال التداول في الامارات": "Recover trading funds in the UAE",
  "استعادة الأموال بعد الاحتيال في الامارات": "Recover funds after fraud in the UAE",
  "أسماء شركات التداول النصابة التي تدعي انها بالامارات": "Names of scam trading companies claiming to be in the UAE",
  "تعرضت للنصب الالكتروني في الامارات": "I was scammed online in the UAE",
  "شركات تداول نصابة تدعي أن مكاتبها في دبي": "Scam trading companies claiming their offices are in Dubai",
  "كيف استرد اموالي من التداول في الامارات": "How do I recover my money from trading in the UAE",
  "محامي استرجاع أموال تداول في الامارات": "Trading fund recovery lawyer in the UAE",
  "هل التداول خدعة ؟ شركات تدعي ان مكتبها في الامارات": "Is trading a scam? Companies claiming their office is in the UAE",
  "هل ممكن استرجع اموال بعد الخسارة مع شركة تداول في الامارات ؟": "Can I recover money after losses with a trading company in the UAE?",
  "وكالة استرداد أموال من شركات التداول والفوركس النصابة التي تدعي انها في الامارات": "Agency to recover funds from scam trading and forex companies claiming to be in the UAE",
  "يطلبون ايداع لحتى اقدر اسحب من شركة تداول في الامارات": "They demand a deposit before I can withdraw from a trading company in the UAE",
};

/** English gloss for an Arabic keyword, or "" if untranslated. */
export const keywordEnglish = (keyword: string): string => KEYWORD_EN[keyword] ?? "";
